server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name fotobooktest24.ru www.fotobooktest24.ru;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/fotobooktest24.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fotobooktest24.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    return 301 https://wedfotobook.ru$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name fotobooktest24.ru www.fotobooktest24.ru;
    server_tokens off;

    return 301 https://wedfotobook.ru$request_uri;
}
